### ISSUE TITLE
Add properties to base yang.

### ISSUE THREAD

**Issue by JohannesGarm** [clicon/clixon-controller#10]
A place for storing properties. Either under services "/ctrl:services/ctrl:properties" or by itself "/ctrl:properties".

**Comment by olofhagsand** [comment]
@JohannesGarm : Added container properties under services, as follows:
```
    container services {
         container properties {
         }
    }
```
But I am not sure this acheives what you want, since there is no element to hold data, you would need to add that in an augment?
Maybe you want a list or a leaf-list there instead?

**Comment by olofhagsand** [comment]
Done, please verify that it works and close it if OK
