### ISSUE TITLE
CLI should allow autocomplete of template variables

### ISSUE THREAD

**Issue by denniswa** [clicon/clixon-controller#100]
CLI should allow autocomplete of template variables if a template has variables.

**Comment by olofhagsand** [comment]
New feature with new YANG with new CLI and netconf syntax.
Therefore putting this in branch https://github.com/clicon/clixon-controller/tree/template-variables
Note that the datastore config is backward-compatible, but as soon as the new version is running, (formal) variables need to be added to all templates before they can be used in an apply.
The CLI/NETCONF apply syntax is not changed.

**Comment by krihal** [comment]
Verified.
