### ISSUE TITLE
show version(s)

### ISSUE THREAD

**Issue by denniswa** [clicon/clixon-controller#105]
CLI to show more details on all the components versions
```
# op show version
Controller: 	0.3.0.PRE
Clixon: 	6.6.0.PRE
CLIgen: 	6.6.0.PRE
```

more details are often needed including pyAPI

**Comment by olofhagsand** [comment]
One could add git commit here but am somewhat reluctant because it would assume a git installation which may not be the case for cross-compiles etc.
A first step should be PYAPI version though

**Comment by olofhagsand** [comment]
See https://github.com/clicon/clixon-pyapi/issues/7

**Comment by krihal** [comment]
Verified.
