### ISSUE TITLE
CLI: Can't change configuration on Juniper QFX devices

### ISSUE THREAD

**Issue by krihal** [clicon/clixon-controller#109]
Nothing is shown below the "config" node when using Juniper QFX.

```
set devices device qfx config ?
```

**Comment by olofhagsand** [comment]
autocli configuration error. 
A rule to enable autocli on junos has the following rule:
```
     <module-name>junos-conf-root</module-name>
```
But the top-level on qfx is `junos-qfx-conf-root`
