### ISSUE TITLE
CLI: Don't show <created>...</created> tags by default

### ISSUE THREAD

**Issue by krihal** [clicon/clixon-controller#110]
There should be a command to show them though. 

Alternative 1: Use NACM.
Alternative 2: Implement `show services X Y detailed`

**Comment by olofhagsand** [comment]
Potential solutions are:
1) autocli:hide. You can see them but you cannot edit them.
2) NACM, have no read access on the creator attributes. But this is a site-specific (and service-specific) config
Therefore (2) could be solved by guidelines only, not part of an upstream controller release

**Comment by krihal** [comment]
Verified.
