### ISSUE TITLE
Optimize: Commands in CLI takes too long time

### ISSUE THREAD

**Issue by krihal** [clicon/clixon-controller#111]
In a system with a large amount of routers CLI commands takes way too long time (>1 second). Same issue when applying templates.

**Comment by olofhagsand** [comment]
Optimized by splitting datastore into several: XMLDB_MULTI

**Comment by olofhagsand** [comment]
Fix optimization: https://github.com/clicon/clixon/commit/9738345f828e15eae6dafd52980da564e882694e
