### ISSUE TITLE
Invalid api-path errors thrown when displayin qfx family device conf in CLI

### ISSUE THREAD

**Issue by JohannesGarm** [clicon/clixon-controller#126]
Attempting to navigate into or show any part of a qfx family device's config results in an invalid api-path error being thrown. Reverting to the eddd75c commit in clixon-controller removed the issue for me. Example:

```
root@nsolab-02[/]# show devices device qfx-32 config configuration
Jun 13 12:16:03.582026: command(root): show devices device qfx-32 config configuration
Jun 13 12:16:03.589761: cli_apipath2xpath: 123: FATAL: Invalid api-path: /clixon-controller:devices/device=qfx-32/config/junos-qfx-conf-root:configuration
CLI command error
```

**Comment by olofhagsand** [comment]
Error was devices with different YANGs, not QFX specifically. Only QFX would probably have worked.
