### ISSUE TITLE
make netconf ssh port to devices configurable

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon-controller#152]
According to RFC 6242 NETCONF over SSH should be done over the netconf subsystem on port 830.
However, the controller is hardcoded to port 22 since most devices seem to use port 22 instead.
This request proposes to make the port configurable so that one can use port 830, even though it is not default.

**Comment by olofhagsand** [comment]
Fixed, please verify

**Comment by getabc** [comment]
Getting the following

```
root@ca-deb-conf[/]# set devices device mydevice port 830
Netconf error: Editing configuration: application unknown-element Failed to find YANG spec of XML node: port with parent: device in namespace: http://clicon.org/controller <bad-element>port</bad-element>

```

**Comment by olofhagsand** [comment]
Works for me:
```
snc@olof-lab[/]# set devices device ptx-ac-4 port 78
snc@olof-lab[/]# 
```
Double check that the correct new YANG is installed eg at `/usr/local/share/controller/main/clixon-controller@2024-08-01.yang`
and that it has the port leaf:
```
        leaf port {
            description
                "Transport port, typically for SSH.
                 RFC6242 stipulates a netconf subsystem over port 830, but in
                 practice many devices defaults to a netconf subsystem over port 22";
            type uint32;
            default 22;
        }
```
(and that all code is updated, recompiled and restarted)

**Comment by getabc** [comment]
I got it working ... will be testing this week.
