### ISSUE TITLE
CLI: default format text | display 

### ISSUE THREAD

**Issue by denniswa** [clicon/clixon-controller#165]
It is not possible to display cli output with | display cli when default format is set to text.

This works with format xml:
user@lab> show configuration services my-service | display cli 

the same command does not work with default format text

lab@lab> default format text
lab@lab> show configuration services my-service | display cli
Nov 28 10:29:44.721294: clixon_xml_parseerror: 195: XML error: xml_parse: line 0: syntax error: at or before: clixon-controller: XML parse error
cligen_eval_pipe_pre child retval:-1
user@lab>

**Comment by krihal** [comment]
Verified.
