### ISSUE TITLE
YANG domains: issues if devices in different domains have identical schemas.

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon-controller#170]
If two devices d0 and d1 have equivalent schemas (eg same os version and yangs) but they are in different domains, D0 and D1.
Then it may happen that both d0 and d1 may be placed in the same domain, D0, say, which leads to follow-up errors.
Problems have been seen in the autocli, with errors on the form:
```
Yang error: Yang "junos-rpc-vpls@2022-01-01" not found in the list of CLICON_YANG_DIRs: No such file or directory
```
This is timing dependent, it is not deterministic.
The cause is an error in `device_shared_yspec()` which does not take domains into account.

**Comment by olofhagsand** [comment]
This is pretty difficult to trigger, you need to have 100s of yangs, the openconfig test yangs cant do it for example.

**Comment by krihal** [comment]
Tested and working.
