### ISSUE TITLE
Autocli consumes lots of memory for some devices

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon-controller#2]
Entering device config for some devices with large YANG models may consume large memory, eg:
```
clixon_cli -m configure
cli# set devices device large-dev config ?

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                             
15351 olof      20   0   11,3g  11,3g   2968 S  40,7   9,0   0:27.46 clixon_cli                        
```
This is also per-device, so that if you enter the next large device you get a new memory hit
Note it is only CLI and does not affect the backend.

**Comment by olofhagsand** [comment]
Clixon 6.3 introduced an auto cli option:
```
  <autocli>                       
     <grouping-treeref>true</grouping-treeref>
```
which reduces the memory footprint by ca a factor of 10 on some machines.

**Comment by krihal** [comment]
Verified, consumes a lot less memory.
