### ISSUE TITLE
Support a loadable mechanism for device profiles

### ISSUE THREAD

**Issue by pheller** [clicon/clixon-controller#21]
For performance reasons and to also facilitate a way to fix potential vendor errors, it might be advantageous to have a mechanism for loadable device profiles.

A standalone tool based on the Clixon-controller schema retrieval could be constructed whereby all schemas are retrieved and stored.  The operator could manipulate the schema as needed and package the result in a format that Clixon-controller could associate with managed devices.

**Comment by olofhagsand** [comment]
Yes, it is needed.
I am unsure on how it should be implemented. 
Should it be part of the configuration?
Or shuld it be a separate directory?
One solution could be to introduce a new "yang/device-class" that a device can belong to. Such a device-class could have information on which YANGs to load independent of the ietf-netconf-monitoring / get-schema mechanism. Essentially a list of modules (or a local file directory?).
Example:
```
device MX1 {
  yang-class juniper-mx;
  ...
}
yang-class jumiper-mx {
  yang-method { netconf-monitoring, explicit-yangs };
  yang-models { // explicit yangs
     openconfig-network-instance.yang;
     ...
  }
  }
}
```

**Comment by olofhagsand** [comment]
Implemented by device-profile and a module-set field for specifying locally available modules to load instead of RFC 6022  dynamic schema retrieval.
However, the feature is not yet fully functional, since it only supports either rfc6022 or local modules, not a combination which may be necessary in some scenarios.

**Comment by olofhagsand** [comment]
Combination should now work
