### ISSUE TITLE
RPC error when using pipe

### ISSUE THREAD

**Issue by krihal** [clicon/clixon-controller#34]
```
debian@khn-dev[/]# set devices device * config interfaces interface | display cli
Aug 29 06:55:32: cli_dbxml_devs_sub: 1456: Config error: api-path syntax error "/clixon-controller:devices/device=r1/config/ietf-interfaces:interfaces/interface": rpc malformed-message malformed key =interface, expected '=restval' : Invalid argument
CLI command error
debian@khn-dev[/]#
```

**Comment by olofhagsand** [comment]
This is because "display cli" is not meaningful for "set" commands.
The solution is to not have "display cli" as a menu option for the set command. Or more general, only have it for commands that generate XML output.

**Comment by krihal** [comment]
> This is because "display cli" is not meaningful for "set" commands.
> The solution is to not have "display cli" as a menu option for the set command. Or more general, only have it for commands that generate XML output.

Same goes for all the other pipe commands such as count, except, grep and tail.

**Comment by olofhagsand** [comment]
Other than show commands removed
@krihal please try again

**Comment by krihal** [comment]
Verified.
