### ISSUE TITLE
CLI show config | display <format> exits over mountpoints with large YANGs

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon-controller#39]
In the cli, some `show config | display xxx` exits eg:
```
cli> show config
<devices xmlns="http://clicon.org/controller">
   <device>
   ....
cli>
cli> show config | display xml
cli>
```

**Comment by olofhagsand** [comment]
After some investigation, there are several problems:
1) The display <format> command binds to YANG which triggers retreiving YANGs from the backend. This causes latency in some cases (large YANGs)
2) There is a fixed timeout (few seconds) before the timeout which is triggered in this case.

Solution:
1) The binding is necessary only for some formats, ie CLI, and should(maybe) also be cached?
2) There should be no fixed timeout

**Comment by olofhagsand** [comment]
Removed timeout and added a ^C

**Comment by krihal** [comment]
Verified, I think.
