### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon-controller#4]
Add templates in the CLI.
Primary approach: evaluate templates outside clixon (ie in python) so that you can apply a powerful template engine, ushc as ninja2, slax, xslt, etc.
Secondary apporach: Very limited template engine inside clixon. Such as only variable substitution.

**Comment by krihal** [comment]
One bug. If I load an invalid XML I'm not allowed to try edit it again.

```
debian@khn-dev[/]# load merge xml
asdasdasdasd
Nov 13 09:48:55: clixon_xml_parseerror: 193: XML error: xml_parse: line 0: syntax error: at or before: asdasdasdasd: XML parse error
CLI command error
```

Trying to load valid XML after the invalid one:
```
debian@khn-dev[/]# load merge xml
Nov 13 09:48:56: Editing configuration: application data-missing <missing-choice xmlns="urn:ietf:params:xml:ns:yang:1">edit-content</missing-choice>: missing-choice : /rpc/edit-config
debian@khn-dev[/]#
```
