### ISSUE TITLE
cl:creator attribute must be persistent

### ISSUE THREAD

**Issue by krihal** [clicon/clixon-controller#54]
If a service is configured and a new chunk of XML is created with the cl:creator attribute set it must be persistent and survive a configuration pull otherwise it's not possible to remove the configuration generated by the service.

**Comment by olofhagsand** [comment]
Persistence fixed in the sense that it survives a configuration pull.
However, killing the controller and restarting it, and then do a pull will not re-create the attributes. It is not persistent in that sense.
