### ISSUE TITLE
"validate push" etc should only use the connected devices

### ISSUE THREAD

**Issue by krihal** [clicon/clixon-controller#58]
There might be devices which are not connected and commands like "validate push" etc should only use devices which are in a connected state.

```
Nov  8 10:15:06: Get configuration: application operation-failed Device is closed: 'ptx10001-10' (try 'connection open' or edit, local commit, and connect)
```

**Comment by olofhagsand** [comment]
Fixed, so that if you set it administrative down, it will not be included in the push set. However if it down because of an error, it will still fail.
Example:
```
olof@totila[/]# set devices device openconfig1 enabled false
olof@totila[/]# commit local
```
