### ISSUE TITLE
YANG memory-footprint optimization

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon-controller#61]
Need to reduce memory footprint of loading many YANG files from many devices.
This may include:

1. Sharing YANG structures between mutliple device mount-points
2. Separating YANG runtime structures from original, such as grouping/uses reference use and read-only fields.
3. Reduce memory footprint of YANG CLI generation

This FR may be split into sub-tasks going forward.

**Comment by krihal** [comment]
Seems to work, closing.
