### ISSUE TITLE
Pre-provisioning

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon-controller#68]
Be able to add and edit configuration for a non-existent/not-yet connected device.  
This includes:

1. Save / Load device data in a persistent way regardless of device pulls
2. Connect to a new device without overwriting config with existing config (only push)
3. Some method to mark a device as off-line / pre-provisioning

**Comment by olofhagsand** [comment]
Some intial steps have been made:
1) You can disable a device (device/enable = false) -> will not make connect/push/pull
2) You can restart the controller withe previous device config (-s running or -s startup)
But pre-provisioning needs some more funtionality, ie, to edit locally and push (overwrite/merge) the locally edited config.
Currently it works as follows:

1. Normal start: 
      - Device connection open + enabled
      - Device XML config in running
      - Device XML bound to YANG
      --> Full functionality
2.  Restart controller with -s running or -s startup. As long as no (re)connect OR device in enable=false, the device is off-line:
     - Device disconnected
      - Device XML config in running
      - Device XML NOT bound to YANG
      --> No CLI editing (NETCONF OK)
3. (Re)connect device (+ enable=true)
      - Device connection open + enabled
      - Device XML config OVERWRITTEN from device
      - Device XML bound to YANG
      --> Full functionality
For pre-provisioning at least the following needs to be done:
1. Off-line CLI editing
2. Merge/replace device config with controller config



    Omstart med -s running
    Så länge man inte ger connect ELLER har enable=false:

    Devices disconnected,
    XML device-config i running
    XML ej bunden till YANG
    Det går inte att editera i CLI:t men i NETCONF går det bra, tjänster osäkert?

    

    Devicen connected
    XML device-confen skrivs över från devicet (ev lokala ändringar borta) men creator attribut är kvar
    XML är bunden till YANG
    -> Full funktionalitet (men lokala ändringar borta)

**Comment by v1shnya** [comment]
Why this feature was closed as completed, do we have pre-provisioning somehow running today?
