### ISSUE TITLE
Using the characters '<' and '>' might cause an invalid diff

### ISSUE THREAD

**Issue by krihal** [clicon/clixon-controller#73]
In Junos I configured a new interface:
```
set interfaces test description "<*>"
```

This causes a diff even if there should be no diff:
```
debian@khn-dev[/]# commit diff
crpd1:
crpd1:
         <interface xmlns="http://yang.juniper.net/junos/conf/root">
            <name>test</name>
-          <description><*></description>
+          <description>></description>
         </interface>
crpd2:
OK
```

**Comment by olofhagsand** [comment]
I have some problems recreating this.

> In Junos I configured a new interface:
> set interfaces test description "<*>"

Do you mean on the device itself, not via the controller?

**Comment by olofhagsand** [comment]
XML encoding missing, and extra hostnames printed.
caveat: fixed in openconfig context not verified on junos as the original issue decribes.
