### ISSUE TITLE
deleting services with commit local leaves orphan creator attributes

### ISSUE THREAD

**Issue by denniswa** [clicon/clixon-controller#86]
When deleting a service and not doing commit (and push to device, eg not running the service code) we end up with orphaned creator tages which might end up deleting or re-creating device config the when the service code (python API) runs again

**Comment by olofhagsand** [comment]
@denniswa can you please clarify?
Are you meaning simply:
1. delete service
2. commit local
--> orphaned attributes?

**Comment by krihal** [comment]
Not relevant any more, closing.
