### ISSUE TITLE
add replace, create and delete operation in templates

### ISSUE THREAD

**Issue by denniswa** [clicon/clixon-controller#99]
Currently templates only do merge, a new feature would be to set different operations in the template to allow delete, create, replace or merge

**Comment by olofhagsand** [comment]
This already seems to work. See https://github.com/clicon/clixon-controller/blob/main/test/test-template.sh.

For example, a template replaces an interface config. It had other fields (such as description) but now only name and type.
In steps:
1) Make a template with eg operation=replace:
```
       <interface nc:operation="replace"> <---
                <name>${NAME}</name>
                <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">${TYPE}</type>
       </interface>            
```
2) Load the template
```
cli# load merge xml <file>
```
3) Commit local
```
cli# commit local
```
4) Apply the template
```
cli# apply template interfaces openconfig* variables NAME z TYPE ianaift:v35
```
5) Commit diff /  commit push:
```
   #cli> show compare
                  <config xmlns="http://openconfig.net/yang/interfaces">
-                    <description>Old description</description>
                  </config>
```

**Comment by krihal** [comment]
Invalid.
